application: pardon-chen
version: live
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /download
  script: download.py
  login:  admin

- url: /.*
  script: index.py

