application: pardon-chen
version: live
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /css
  static_dir: css
  secure: always

- url: /js
  static_dir: js
  secure: always

- url: /download
  script: download.py
  login:  admin
  secure: always

- url: /.*
  script: index.py
  secure: always

